package Grimlock::App::Web::Model::Database;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Grimlock::App::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=grimlock_test;host=localhost',
        user => 'postgres',
        password => 'lairdo',
        AutoCommit => q{1},
        cursor_class => q{DBIx::Class::Cursor::Cached},
        quote_names => q{1},
    }
);

=head1 NAME

Grimlock::App::Web::Model::Database - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Grimlock::App::Web>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Grimlock::App::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Devin Austin

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
